brainbunny-backend-django-master/base/urls.py
from django.urls import path
from django.conf.urls import handler404
from . import views

handler404 = views.custom_404

urlpatterns = [
    path('', views.home, name='home'),
    path('leaderboard', views.leaderboard_view, name='leaderboard'),
    path('dashboard', views.dashboard_view, name='dashboard'),
    path('message/<int:id>', views.message_view, name='message'),
    path('about', views.about_view, name='about'),
    path('blogs', views.blogs_view, name='blogs'),
    path('blogs/<str:blog_id>', views.blog_view, name='blog'),
    path('contact', views.contact_view, name='contact'),
    path('terms_and_conditions', views.terms_conditions_view, name='terms_conditions'),
    path('downloads', views.downloads_view, name='downloads'),
    path('search/users', views.search_users_view, name='search_users'),
]

brainbunny-backend-django-master/brainbunny/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('user/', include('account.urls')),
    path('quiz/', include('quiz.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

brainbunny-backend-django-master/quiz/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all_quiz', views.all_quiz_view, name='all_quiz'),
    path('search/<str:category>', views.search_view, name='search'),
    path('<int:quiz_id>', views.quiz_view, name='quiz'),
    path('<int:submission_id>/result/', views.quiz_result_view, name='quiz_result'),
]

brainbunny-backend-django-master/quiz/models.py
from django.db import models
import pandas as pd
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver
from smart_open import open
import io

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=15)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    quiz_file = models.FileField(upload_to='quiz/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return self.title

    # call the function on quiz save
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.quiz_file:
            self.import_quiz_from_excel()

    # function to extract excel file
    def import_quiz_from_excel(self):
        # Use self.quiz_file.url to get the S3 file URL
        s3_url = self.quiz_file.url

        # Use smart_open to read the Excel file from S3
        with open(s3_url, 'rb') as file:
            # Load the Excel file content into a pandas DataFrame
            df = pd.read_excel(io.BytesIO(file.read()))

        # iterate over the each row
        for index, row in df.iterrows():
            # extract question text, choices and correct answer from the row
            question_text = row['Question']
            choice1 = row['A']
            choice2 = row['B']
            choice3 = row['C']
            choice4 = row['D']
            correct_answer = row['Answer']

            # create the question object
            question = Question.objects.get_or_create(quiz=self, text=question_text)

            # create choices objects
            choice_1 = Choice.objects.get_or_create(question=question[0], text=choice1, is_correct=correct_answer == 'A')
            choice_2 = Choice.objects.get_or_create(question=question[0], text=choice2, is_correct=correct_answer == 'B')
            choice_3 = Choice.objects.get_or_create(question=question[0], text=choice3, is_correct=correct_answer == 'C')
            choice_4 = Choice.objects.get_or_create(question=question[0], text=choice4, is_correct=correct_answer == 'D')

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text[:50]
    

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.question.text[:50]}, {self.text[:20]}"

class QuizSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}, {self.quiz.title}"

class UserRank(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rank = models.IntegerField(null=True, blank=True)
    total_score = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f"{self.rank}, {self.user.username}"

    @receiver(post_save, sender=QuizSubmission)
    def update_leaderboard(sender, instance, created, **kwargs):
        if created:
            update_leaderboard()



def update_leaderboard():
    # Count the sum of scores for all users
    user_scores = (QuizSubmission.objects.values('user').annotate(total_score=Sum('score')).order_by('-total_score'))

    # Update rank based on the sorted list
    rank = 1
    for entry in user_scores:
        user_id = entry['user']
        total_score = entry['total_score']

        user_rank, created = UserRank.objects.get_or_create(user_id=user_id)
        user_rank.rank = rank
        user_rank.total_score = total_score
        user_rank.save()

        rank += 1

brainbunny-backend-django-master/quiz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from account.models import Profile
from .models import Quiz, Category
from django.db.models import Q
from quiz.models import QuizSubmission
from django.contrib import messages

# Create your views here.

@login_required
def all_quiz_view(request):

    quizzes = Quiz.objects.order_by('-created_at')
    categories = Category.objects.all()

    context = {"quizzes": quizzes, "categories": categories}
    return render(request, 'all-quiz.html', context)

@login_required
def search_view(request, category):

    # search by search bar
    if request.GET.get('q') != None:
        q = request.GET.get('q')
        query = Q(title__icontains=q) | Q(description__icontains=q)
        quizzes = Quiz.objects.filter(query).order_by('-created_at')
    
    # search by category
    elif category != " ":
        quizzes = Quiz.objects.filter(category__name=category).order_by('-created_at')
    
    else:
        quizzes = Quiz.objects.order_by('-created_at')


    categories = Category.objects.all()

    context = {"quizzes": quizzes, "categories": categories}
    return render(request, 'all-quiz.html', context)

@login_required
def quiz_view(request, quiz_id):

    quiz = get_object_or_404(Quiz, pk=quiz_id)

    if request.method == "POST":
        
        # Get the score
        score = int(request.POST.get('score', 0))
        
        # save the new quiz submission
        submission = QuizSubmission(user=request.user, quiz=quiz, score=score)
        submission.save()

        return redirect('quiz_result', submission_id=submission.id)

    return render(request, 'quiz.html', {'quiz': quiz})

@login_required
def quiz_result_view(request, submission_id):

    submission = get_object_or_404(QuizSubmission, pk=submission_id, user=request.user)
    context = {'submission': submission}
    return render(request, 'quiz-result.html', context)

brainbunny-backend-django-master/templates/about.html
{% extends 'index.html' %}
{% block title %}About Us - BrainBunny{% endblock title %}

{% block content %}

<h1 class="display-4 text-center my-5">About Us</h1>

<main>
    <div class="container col-md-8 col-sm-12">
        <section class="app-description">
            <h2>Welcome to BrainBunny</h2>
            <p>
                BrainBunny is an exciting web app that brings you the latest and hottest quiz topics in the world of
                technology.
                Sign up now to challenge your knowledge, learn new things, and have fun with our engaging quizzes.
            </p>
        </section>

        <section class="how-it-works">
            <h2>How It Works</h2>
            <p>
                BrainBunny offers a simple and intuitive user interface that allows you to:
            </p>
            <ul>
                <li>Sign up and create your personalized account.</li>
                <li>Choose from a variety of trending quiz topics in the technology domain.</li>
                <li>Participate in time-limited quizzes and answer questions to rank yourself on BrainBunny.</li>
                <li>Track your progress and compete with other tech enthusiasts on the leaderboard.</li>
            </ul>
        </section>
    </div>
</main>

{% endblock content %}

brainbunny-backend-django-master/templates/confirm.html
{% extends 'index.html' %}

{% block title %}@{{request.user.username}} Profile Delete Confirmation - BrainBunny{% endblock title %}

{% block content %}


<h1 class="display-4 text-center my-5">Confirmation Page</h1>

  <div class="container">
    <form action="" method="POST" class="">
        {% csrf_token %}
        <p class="fs-4"><b>@{{request.user.username}}</b>, Are you sure you want to delete your profile??</p>
        <a href="{% url 'profile' request.user.username %}" class="btn btn-success" type="button">Back to Profile</a>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
  </div>

{% endblock content %}

brainbunny-backend-django-master/templates/downloads.html
{% extends 'index.html' %}
{% block title %}Downloads - BrainBunny{% endblock title %}

{% block content %}
<h1 class="display-4 text-center my-5">Downloads</h1>

<main>
    <div class="container col-md-8 col-sm-12">
        <div class="download-item mb-4">
            <h2 class="">Research Paper 1</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                explicabo eos molestias enim itaque, quis nam.</p>
            <a href="" class="btn btn-primary">Download</a>
            <hr>
        </div>
        <div class="download-item mb-4">
            <h2>Reports</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                explicabo eos molestias enim itaque, quis nam.</p>
            <a href="" class="btn btn-primary">Download</a>
            <hr>
        </div>
        <div class="download-item mb-4">
            <h2>Research Paper 1</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus odio facere accusantium rem
                explicabo eos molestias enim itaque, quis nam.</p>
            <a href="" class="btn btn-primary">Download</a>
            <hr>
        </div>
    </div>
</main>

{% endblock content %}

brainbunny-backend-django-master/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Welcome to BrainBunny{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css"
        integrity="sha512-ZnR2wlLbSbr8/c9AgLg3jQPAattCUImNsae6NHYnS9KrIwRdcY9DxFotXhNAKIKbAXlRnujIqUWoXXwqyFOeIQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    {% include "components/navbar.html" %}

    {% block content %}

    {% endblock content %}

    {% include "components/footer.html" %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>

    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
</body>

</html>

brainbunny-backend-django-master/templates/leaderboard.html
{% extends 'index.html' %}

{% block title %}Leaderboard - BrainBunny{% endblock title %}

{% block content %}
<div class="container text-center">
    <h1 class="display-4 text-center my-5">Leaderboard</h1>

    <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 mx-3">
        {% if leaderboard_users|length == 0 %}
        <div class="col-lg-4 position-relative mb-4">
            <h4 class="text-center text-danger">No User Available on Leaderboard!!</h4>
        </div>
        {% else %}
        {% for rank in leaderboard_users %}
        <div class="col-lg-4 position-relative mb-4">
            <img src="{{rank.user.profile.profile_img.url}}" class="img-fluid" width="150" height="150" alt="user-profile">
            <span class="position-absolute top-0 start-90 translate-middle badge rounded-pill bg-success">{{forloop.counter}}</span>
            <h2 class="fw-normal">@{{rank.user.username}}</h2>
            <p>{{rank.user.profile.bio|truncatewords:5}}</p>
            <p><a class="btn btn-secondary" href="{% url 'profile' rank.user.username  %}">View Profile »</a></p>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}

brainbunny-backend-django-master/templates/message.html
{% extends 'index.html' %}
{% block title %}Message from @{{message.user.username}} - BrainBunny{% endblock title %}

{% block content %}

<h1 class="display-4 text-center my-5">Message From @{{message.user.username}}</h1>

    <main>
        <div class="container col-md-8 col-sm-12">
            <article>
                <sub>From</sub>
                <p title="click to see profile"><a href="{% url 'profile' message.user.username %}">@{{message.user.username}}</a></p>
                <sub>Received At</sub>
                <p>{{message.created_at}}</p>
                <sub>Subject</sub>
                <p>{{message.subject}}</p>
                <sub>Message</sub>
                <p>{{message.message}}</p>
            </article>
        </div>
    </main>

{% endblock content %}

brainbunny-backend-django-master/templates/profile-edit.html
{% extends 'index.html' %}

{% block title %}@{{request.user.username}} Profile Edit - BrainBunny{% endblock title %}

{% block content %}

  <h1 class="display-4 text-center my-5">Edit Profile</h1>


  <div class="container">
    <div class="row row-cols-sm-1 row-cols-lg-3 container">
      <div class="col-12">
      </div>
      <div class="col-12">


        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3 d-flex justify-content-center">
                <img src="{{user_profile.profile_img.url}}" alt="profile-pic" width="150" height="150" class="rounded-circle">
            </div>

            <div class="mb-3">
                {% for message in messages %}
                <h5 class="text-danger">{{message}}</h5>
                {% endfor %}
              </div>
          <div class="mb-3">
            <label for="exampleInputImage" class="form-label visually-hidden">Profile Image</label>
            <input type="file" name="profile_img" class="form-control" id="exampleInputImage">
          </div>
          <div class="mb-3">
            <label for="exampleInputFirstName" class="form-label visually-hidden">First Name</label>
            <input type="text" name="firstname" value="{{user_profile.user.first_name}}" class="form-control" id="exampleInputFirstName" placeholder="First Name" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputLastName" class="form-label visually-hidden">Last Name</label>
            <input type="text" name="lastname" value="{{user_profile.user.last_name}}" class="form-control" id="exampleInputLastName" placeholder="Last Name" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputEmail2" class="form-label visually-hidden">Email</label>
            <input type="email" name="email" value="{{user_profile.user.email}}" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp"
              placeholder="Email" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputUsername1" class="form-label visually-hidden">Username</label>
            <input type="text" name="username" value="{{user_profile.user.username}}" class="form-control" id="exampleInputUsername1" aria-describedby="emailHelp"
              placeholder="Username" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputLocation" class="form-label visually-hidden">Location</label>
            <input type="text" name="location" value="{{user_profile.location}}" class="form-control" id="exampleInputLocation" placeholder="Location" required>
          </div>
          
          <div class="mb-3">
            <label for="exampleInputGender" class="form-label visually-hidden">Gender</label>
            <select class="form-select form-control" name="gender" id="exampleInputGender" aria-label="Default select example" required>
                <option selected>Choose Your Gender</option>
                <option {% if user_profile.gender == 'Male' %}selected{% endif %} value="Male">Male</option>
                <option {% if user_profile.gender == 'Female' %}selected{% endif %} value="Female">Female</option>
                <option {% if user_profile.gender == 'Other' %}selected{% endif %} value="Other">Other</option>
              </select>
          </div>

          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label visually-hidden">Your Bio</label>
            <textarea class="form-control" name="bio" id="exampleFormControlTextarea1" rows="3" placeholder="Your Bio" required>{{user_profile.bio}}</textarea>
          </div>
          
          <button type="submit" class="btn btn-success">Save Profile</button>
        </form>
      </div>
      <div class="col-12">
      </div>
    </div>
  </div>

{% endblock content %}

brainbunny-backend-django-master/templates/quiz-result.html
{% extends 'index.html' %}

{% load custom_filters %}

{% block title %}Result for {{submission.quiz.title}} - BrainBunny{% endblock title %}

{% block content %}

    <style>
        .result-card {
            max-width: 400px;
            margin: auto;
        }

        .result-card .card-body {
            padding: 1.5rem;
        }
        
        .questions {
            user-select: none;
        }
    </style>

    <div class="container my-5">

        <div class="result-card">
            <div class="card shadow">
                <div class="card-header text-center bg-primary text-white">
                    <h5>Quiz Result Summary</h5>
                </div>
                <div class="card-body">
                    <p><strong>Name:</strong> {{ submission.user.profile.full_name }}</p>
                    <hr>
                    <p><strong>Quiz:</strong> {{ submission.quiz.title|title }}</p>
                    <p><strong>Total Questions:</strong> {{ submission.quiz.question_set.count }}</p>
                    <p><strong>Total Correct Answers:</strong> {{ submission.score }}</p>
                    <p><strong>Total Incorrect Answers:</strong> {{ submission.quiz.question_set.count|subtract:submission.score }}</p>
                    <p><strong>Submit at:</strong> {{ submission.submitted_at|timesince }} ago</p>
                </div>
                <div class="card-footer text-center">
                    <a href="{% url 'all_quiz' %}" class="btn btn-primary">All Quiz</a>
                    <a href="{% url 'quiz' submission.quiz.id %}" class="btn btn-primary">Retake</a>
                </div>
            </div>
        </div>


        <div class="questions my-4">
            {% for question in submission.quiz.question_set.all %}
            <div class="card mb-2 question">
                <div class="card-header fw-bold">
                    Question {{forloop.counter}}
                </div>
                <div class="card-body">
                    <p class="card-text">{{question.text}}</p>
                    {% for option in question.choice_set.all %}
                    <div class="form-check">
                        <label class="form-check-label" for="{{option.id}}">
                            <input class="form-check-input" disabled {% if option.is_correct %}checked{% endif %} value="{{option.text}}" type="radio" name="{{option.question.id}}" id="{{option.id}}">
                            {{option.text}}
                        </label>
                        {% if option.is_correct %}
                        <span class="visually-hidden correct-answer">{{option.text}}</span>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

    </div>

{% endblock content %}

brainbunny-backend-django-master/templates/quiz.html
{% extends 'index.html' %}

{% block title %}{{quiz.title}} - BrainBunny{% endblock title %}

{% block content %}
    <style>
        .questions {
            user-select: none;
        }
    </style>

    <h1 class="display-4 text-center my-5">{{quiz.title}} - ({{quiz.question_set.all|length}})</h1>
    <p class="fs-4 text-center container">{{quiz.description}}</p>

    <div class="container">
        <div class="d-flex justify-content-between">
            <span class="fs-5">{{quiz.created_at}}</span>
            <span class="fs-5" id="timer">10:00</span>
        </div>

        {% for message in messages %}
        <div id="message-div">
            <h4 class="text-center text-success">{{message}}</h4>
        </div>
        {% endfor %}


        <div class="questions my-4">
            {% for question in quiz.question_set.all %}
            <div class="card mb-2 question">
                <div class="card-header fw-bold">
                    Question {{forloop.counter}}
                </div>
                <div class="card-body">
                    <p class="card-text">{{question.text}}</p>
                    {% for option in question.choice_set.all %}
                    <div class="form-check">
                        <label class="form-check-label" for="{{option.id}}">
                            <input class="form-check-input" value="{{option.text}}" type="radio" name="{{option.question.id}}" id="{{option.id}}">
                            {{option.text}}
                        </label>
                        {% if option.is_correct %}
                        <span class="visually-hidden correct-answer">{{option.text}}</span>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        <form action="" method="post" id="quiz-form">
            {% csrf_token %}
            <!-- hidden input field for score -->
            <input type="hidden" name="score" value="0" id="user-score">

            <!-- submit button -->
            <button type="submit" class="btn btn-primary" id="submit-button">Submit the quiz</button>
        </form>

    </div>

<script>
    // Elements
    var submitButton = document.getElementById("submit-button");
    var timerSpan = document.getElementById("timer");
    var quizForm = document.getElementById("quiz-form");
    var questions = document.querySelectorAll(".question");
    var userScoreInput = document.getElementById("user-score");

    quizDuration = (questions.length) * 60; // convert in seconds
    
    // Update Timer
    function updateTimer() {
        var minutes = Math.floor(quizDuration / 60);
        var seconds = quizDuration % 60;

        timerSpan.innerText = minutes + "m" + seconds + 's';

        // Check if the time ended
        if (quizDuration <= 0) {
            // Automatically Submit the quiz
            clearTimeout(quizTimerId);
            submitQuiz();
        } else if (document.getElementById("message-div")) {
            clearTimeout(quizTimerId);
            highlightCorrectAnswers();
        } else {
            // decrement the timer value by 1s
            quizDuration--;
        }
    }

    // Function to submit the quiz
    function submitQuiz() {
        // Calculate the score
        calculateScore();

        // Submit the quiz
        quizForm.submit();
    }

    // Check right answer and then calculate the score
    function calculateScore() {
        var score = 0;

        // Loop through each question
        questions.forEach(question => {
            var selectedInput = question.querySelector('input:checked');
            var correctAnswer = question.querySelector(".correct-answer").innerText;

            // Check if the answer is correct or not
            if (selectedInput && selectedInput.value === correctAnswer) {
                score += 1;
            }
        });

        // Update the hidden input field with score in form
        userScoreInput.value = score;
    }

    // highlight correct answer while showing result
    function highlightCorrectAnswers() {
        questions.forEach(question => {
            var correctAnswer = question.querySelector(".correct-answer");
            correctAnswer.previousElementSibling.querySelector("input").classList.add("bg-success");
            correctAnswer.previousElementSibling.classList.add("fw-bold");
        });

        // disable submit button
        submitButton.disabled = true;

        // disabel all options
        var options = document.querySelectorAll(".form-check-input");
        options.forEach(option => {
            option.disabled = true;
        });
    }

    // Attach Event Listener to Submit button
    submitButton.addEventListener("click", submitQuiz);

    // Timer Interval
    quizTimerId = setInterval(updateTimer, 1000);
</script>


{% endblock content %}

brainbunny-backend-django-master/templates/quiz_result.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz Result Summary</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .result-card {
            max-width: 400px;
            margin: auto;
        }

        .result-card .card-body {
            padding: 1.5rem;
        }
    </style>
</head>

<body>
    <div class="container my-5">
        <div class="result-card">
            <div class="card shadow">
                <div class="card-header text-center bg-primary text-white">
                    <h5>Quiz Result Summary</h5>
                </div>
                <div class="card-body">
                    <p><strong>Name:</strong> John Doe</p>
                    <hr>
                    <p><strong>Total Questions:</strong> 20</p>
                    <p><strong>Total Correct Answers:</strong> 15</p>
                    <p><strong>Total Incorrect Answers:</strong> 5</p>
                </div>
                <div class="card-footer text-center">
                    <button class="btn btn-primary">View Detailed Report</button>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

brainbunny-backend-django-master/templates/register.html
{% extends 'index.html' %}

{% block title %}Register Page - BrainBunny{% endblock title %}

{% block content %}

  <h1 class="display-4 text-center my-5">Register</h1>

  <div class="container">
    <div class="row row-cols-sm-1 row-cols-lg-3 container">
      <div class="col-12">
      </div>
      <div class="col-12">
        <div>
          {% for message in messages %}
          <h5 class="text-danger">{{message}}</h5>
          {% endfor %}
        </div>

        <form method="POST" action="">
          {% csrf_token %}
          <div class="mb-3">
            <label for="exampleInputEmail2" class="form-label visually-hidden">Email</label>
            <input type="email" name="email" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp"
              placeholder="Email" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputUsername1" class="form-label visually-hidden">Username</label>
            <input type="text" name="username" class="form-control" id="exampleInputUsername1" aria-describedby="emailHelp"
              placeholder="Username" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label visually-hidden">Password</label>
            <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password" required>
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword2" class="form-label visually-hidden">Repeat Password</label>
            <input type="password" name="password2" class="form-control" id="exampleInputPassword2" placeholder="Repeat Password" required>
          </div>
          <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
            <label class="form-check-label" for="exampleCheck1"><a href="{% url 'terms_conditions' %}">Terms and Conditions</a></label>
          </div>
          <button type="submit" class="btn btn-primary">Register</button>
          <p class="my-4">Already a member? <b><a href="{% url 'login' %}">Login</a></b></p>
        </form>
      </div>
      <div class="col-12">
      </div>
    </div>
  </div>

{% endblock content %}